### PR TITLE
Add files via upload

### LINKED ISSUE #8: 6. Testing Data Processing

### PR DESCRIPTION
**Pull request by zhangqianalone**
This code is written to test functions

### CODE REVIEW

**Comment by wintelestr** [comment]
Good testing codes!

**Comment by JinsenLou** [comment]
Good design of the unit test, maybe showing the result would be better

**Comment by dtdoris** [comment]
Nice structure and clear comments. Good job.

**Comment by 9264Y** [comment]
Well done. Add more comments

**Pull request merged**
