### PR TITLE
4 4 water content computing

### LINKED ISSUE #4: 4. Water Content Computing

### PR DESCRIPTION
**Pull request by wintelestr**
Completed water content calculation at a constant temperature of 25 degrees and developed the GUI for the water content page.

### CODE REVIEW

**Comment by JinsenLou** [comment]
Nice programming for this water computing module, well done

**Comment by zhangqianalone** [comment]
Agree to merge to the main, good codes

**Comment by 9264Y** [comment]
Easy to understand. Excellent structure

**Comment by dtdoris** [comment]
Agree to merge. Clear to figure out the formulas and corresponding code functions.

**Pull request merged**
