### PR TITLE
Update meshCreation.py

### LINKED ISSUE #20: 2. Creation of Domain and Mesh

### PR DESCRIPTION
**Pull request by 9264Y**
Improve the function of create_mesh

### CODE REVIEW

**Comment by wintelestr** [comment]
Good Codes with a clear structure.

**Comment by zhangqianalone** [comment]
Good code to complete domain and mesh step.

**Comment by JinsenLou** [comment]
Well structured and documented code

**Comment by dtdoris** [comment]
Great work and clear comments of code.

**Pull request merged**
