### PR TITLE
9 9 testing water content computing

### LINKED ISSUE #11: 9. Testing Water Content Computing

### PR DESCRIPTION
**Pull request by wintelestr**
The water content calculation module has passed the testing

### CODE REVIEW

**Comment by 9264Y** [comment]
Good job! Passed all the tests

**Comment by zhangqianalone** [comment]
Nice work, the test code is perfect!

**Comment by JinsenLou** [comment]
Brief and efficient test unit, maybe results to present here

**Comment by dtdoris** [comment]
Easy to identify the function of each block. Good job.

**Pull request merged**
